name: Test Cymometer

on:
  push:
    branches:
      - master
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.4'

    services:
      redis:
        image: redis
        ports: ["6379:6379"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run the default task
      run: bundle exec rake
      env:
        REDIS_URL: redis://localhost:6379
